//! Offline licence keys.
//!
//! The local app is free and stays free. A licence buys two things: the right to use Capture
//! Studio commercially, and quiet — the occasional reminder stops. It unlocks no features,
//! because gating features would make the free app worse, which is not the deal.
//!
//! Verification is a signature check against a public key compiled into this binary. There is
//! no licence server, no activation request, nothing to phone home to — the local app makes
//! no network calls at all and that has to stay true. The cost of that choice is that a key
//! cannot be revoked once issued; at this price point, chasing revocation would cost more
//! than the fraud it prevents.
//!
//! ## Key format
//! `base64url( payload || signature )`, where signature is 64 bytes of Ed25519 over payload:
//! ```text
//! payload = [version: u8][kind: u8][issued: u32 LE, days since 1970-01-01][name: UTF-8]
//! ```
//! The name has no length prefix — it runs to the end of the payload, and the payload runs to
//! 64 bytes before the end of the whole blob.

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::sync::Mutex;
use tauri::State;

use crate::library::default_library_dir;

/// Public half of the signing key, generated by `cargo run --example license_tool -- keygen`.
///
/// All zeroes means licensing has not been set up yet for this build: every key is then
/// rejected with an explicit message rather than a confusing signature error.
const PUBLIC_KEY: [u8; 32] = [0u8; 32];

const KEY_VERSION: u8 = 1;
const SIG_LEN: usize = 64;

/// Days of use before the first reminder. A month is long enough that anyone still using the
/// app has decided they like it, and short enough to be worth asking.
const NUDGE_AFTER_DAYS: i64 = 30;
/// Minimum gap between reminders. Weekly, not daily — this is a reminder, not a campaign.
const NUDGE_EVERY_DAYS: i64 = 7;

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
#[serde(rename_all = "camelCase")]
pub struct LicenseFile {
    /// The key exactly as the user pasted it, so it can be re-verified on every launch
    /// rather than trusting a stored "yes it was valid once" flag.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// First launch, as `YYYY-MM-DD`. Written once and then left alone.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_run: Option<String>,
    /// Last time the reminder was shown or dismissed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_nudge: Option<String>,
}

pub type LicenseState = Mutex<LicenseFile>;

/// What the UI needs to know. Deliberately a flat snapshot — the frontend should never have
/// to re-derive "should I nag" from raw dates.
#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct LicenseStatus {
    pub licensed: bool,
    pub name: Option<String>,
    /// "personal" | "commercial"
    pub kind: Option<String>,
    pub issued: Option<String>,
    pub days_used: i64,
    /// True only when unlicensed, past the grace period, and due another reminder.
    pub should_nudge: bool,
}

#[derive(Clone, Debug)]
pub struct LicenseInfo {
    pub name: String,
    pub kind: String,
    pub issued: String,
}

fn license_path() -> PathBuf {
    default_library_dir().join("license.json")
}

fn today() -> chrono::NaiveDate {
    chrono::Local::now().date_naive()
}

fn parse_date(s: &Option<String>) -> Option<chrono::NaiveDate> {
    s.as_deref()
        .and_then(|d| chrono::NaiveDate::parse_from_str(d, "%Y-%m-%d").ok())
}

/// Load the licence file, stamping the first-run date if this is a fresh install.
pub fn load() -> LicenseFile {
    let mut file: LicenseFile = std::fs::read_to_string(license_path())
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    if file.first_run.is_none() {
        file.first_run = Some(today().format("%Y-%m-%d").to_string());
        save(&file);
    }
    file
}

fn save(file: &LicenseFile) {
    let dir = default_library_dir();
    let _ = std::fs::create_dir_all(&dir);
    if let Ok(json) = serde_json::to_string_pretty(file) {
        let _ = std::fs::write(license_path(), json);
    }
}

/// Check a key's signature and unpack what it says.
pub fn verify(key: &str) -> Result<LicenseInfo, String> {
    if PUBLIC_KEY == [0u8; 32] {
        return Err("This build has no licensing key configured.".into());
    }
    // Users paste keys out of emails, which adds line breaks and stray spaces.
    let cleaned: String = key.chars().filter(|c| !c.is_whitespace()).collect();
    if cleaned.is_empty() {
        return Err("Enter your licence key.".into());
    }
    let blob = URL_SAFE_NO_PAD
        .decode(cleaned.as_bytes())
        .map_err(|_| "That doesn't look like a licence key.".to_string())?;
    if blob.len() <= SIG_LEN {
        return Err("That licence key is incomplete.".into());
    }

    let (payload, sig) = blob.split_at(blob.len() - SIG_LEN);
    let verifying = VerifyingKey::from_bytes(&PUBLIC_KEY)
        .map_err(|_| "This build's licensing key is invalid.".to_string())?;
    let signature = Signature::from_slice(sig)
        .map_err(|_| "That licence key is malformed.".to_string())?;
    verifying
        .verify(payload, &signature)
        .map_err(|_| "That licence key isn't valid.".to_string())?;

    // Only parsed after the signature checks out, so nothing here is attacker-controlled.
    if payload.len() < 6 {
        return Err("That licence key is malformed.".into());
    }
    if payload[0] != KEY_VERSION {
        return Err("That licence key is for a newer version of Capture Studio.".into());
    }
    let kind = match payload[1] {
        1 => "personal",
        2 => "commercial",
        _ => return Err("That licence key has an unknown type.".into()),
    };
    let days = u32::from_le_bytes([payload[2], payload[3], payload[4], payload[5]]);
    let issued = chrono::DateTime::from_timestamp(days as i64 * 86_400, 0)
        .map(|d| d.date_naive().format("%Y-%m-%d").to_string())
        .unwrap_or_default();
    let name = String::from_utf8_lossy(&payload[6..]).to_string();

    Ok(LicenseInfo { name, kind: kind.into(), issued })
}

fn status_from(file: &LicenseFile) -> LicenseStatus {
    // Re-verified every time rather than trusting a cached flag, so a corrupted or
    // hand-edited file degrades to "unlicensed" instead of granting a licence.
    let info = file.key.as_deref().and_then(|k| verify(k).ok());
    let first = parse_date(&file.first_run).unwrap_or_else(today);
    let days_used = (today() - first).num_days().max(0);

    let due = match parse_date(&file.last_nudge) {
        Some(last) => (today() - last).num_days() >= NUDGE_EVERY_DAYS,
        None => true,
    };

    LicenseStatus {
        licensed: info.is_some(),
        name: info.as_ref().map(|i| i.name.clone()),
        kind: info.as_ref().map(|i| i.kind.clone()),
        issued: info.as_ref().map(|i| i.issued.clone()),
        days_used,
        should_nudge: info.is_none() && days_used >= NUDGE_AFTER_DAYS && due,
    }
}

#[tauri::command]
pub fn get_license_status(state: State<LicenseState>) -> Result<LicenseStatus, String> {
    let file = state.lock().map_err(|e| e.to_string())?;
    Ok(status_from(&file))
}

#[tauri::command]
pub fn activate_license(state: State<LicenseState>, key: String) -> Result<LicenseStatus, String> {
    // Verified before it is stored, so an invalid key never lands in the file at all.
    verify(&key)?;
    let mut file = state.lock().map_err(|e| e.to_string())?;
    file.key = Some(key.chars().filter(|c| !c.is_whitespace()).collect());
    save(&file);
    Ok(status_from(&file))
}

#[tauri::command]
pub fn remove_license(state: State<LicenseState>) -> Result<LicenseStatus, String> {
    let mut file = state.lock().map_err(|e| e.to_string())?;
    file.key = None;
    save(&file);
    Ok(status_from(&file))
}

/// Record that the reminder was shown, so the next one is a week away.
#[tauri::command]
pub fn snooze_license_nudge(state: State<LicenseState>) -> Result<(), String> {
    let mut file = state.lock().map_err(|e| e.to_string())?;
    file.last_nudge = Some(today().format("%Y-%m-%d").to_string());
    save(&file);
    Ok(())
}
